name: '@guardian/post-release-action'
description: 'A GitHub action to handle the post release process for repositories with branch protection'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  github-token:
    required: true
    description: A GitHub token
branding:
  icon: 'package'
  color: 'gray-dark'
