name: '@guardian/actions-merge-workflow-changes-to-protected-branch'
description: 'A GitHub action to open, approve and merge a PR with changes generated during a workflow action on a protected branch'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  github-token:
    description: A GitHub token
    required: true
  package-manager:
    description: 'The name of the package manager used: npm, yarn'
    required: false
    default: npm
  pr-author:
    description: The author of version bump PRs
    required: false
    default: guardian-ci
  pr-prefix:
    description: The prefix to add to version bump PRs (note that a space will be added after the value)
    required: false
    default: 'chore(release):'
  release-branch:
    description: The branch which releases are run from
    required: false
    default: main
  branch-prefix:
    description: The prefix to add to the branch name to commit version bump changes to
    required: false
    default: release-
  commit-user:
    description: The username of the user to commit version bump changes with
    required: false
    default: guardian-ci
  commit-email:
    description: The email of the user to commit version bump changes with
    required: false
    default: guardian-ci@users.noreply.github.com
branding:
  icon: 'package'
  color: 'gray-dark'
