name: '@guardian/actions-merge-release-changes-to-protected-branch'
description: 'A GitHub action to open, approve and merge a PR of changes generated during a release on a protected branch'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  github-token:
    description: A GitHub token
    required: true
  package-manager:
    description: 'The name of the package manager used: npm, yarn'
    required: false
    default: npm
  npm-lockfile-version:
    description: The lockfile version in use if npm is the selected package-manager
    required: false
    default: '1'
  additional-changes:
    description: 'A JSON object of additional changes where the key is a filename and the value is an array of acceptable changes in that file e.g. `{"README.md": ["-  \"version\": \"", "+  \"version\": \""]}`. Use the value "*" to allow any changes to a particular file.'
    required: false
    default: '{}'
  pr-author:
    description: The author of version bump PRs
    required: false
    default: guardian-ci
  pr-prefix:
    description: The prefix to add to version bump PRs (note that a space will be added after the value)
    required: false
    default: 'chore(release):'
  release-branch:
    description: The branch which releases are run from
    required: false
    default: main
  branch-prefix:
    description: The prefix to add to the branch name to commit version bump changes to
    required: false
    default: release-
  commit-user:
    description: The username of the user to commit version bump changes with
    required: false
    default: guardian-ci
  commit-email:
    description: The email of the user to commit version bump changes with
    required: false
    default: guardian-ci@users.noreply.github.com
branding:
  icon: 'package'
  color: 'gray-dark'
