name: '@guardian Release'
description: 'Run the CD process for Guardian repositories that define publishable libraries'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
