name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'npm'
      - run: npm ci
      - run: ./script/build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'npm'
      - run: npm ci
      - run: ./script/lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: guardian/actions-setup-node@v2.4.1
        with:
          cache: 'npm'
      - run: npm ci
      - run: ./script/test
